/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arcade;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import prueba.Conexion;

/**
 *
 * @author DanKuzo
 */
public class Arcade extends javax.swing.JFrame {

    Login l = new Login();
    public static String idproducto;

    public static String getIdproducto() {
        return idproducto;
    }

    public static void setIdproducto(String idproducto) {
        Arcade.idproducto = idproducto;
    }

    /**
     * Creates new form NewJFrame
     */
    public Arcade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Comprar = new javax.swing.JMenuItem();
        Rentar = new javax.swing.JMenuItem();
        logo = new javax.swing.JLabel();
        saludo = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        cerrarS = new javax.swing.JButton();
        eslogan = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VentaRentaPro = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PersonasRenta = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        Eliminar = new javax.swing.JMenu();
        Actualizar = new javax.swing.JMenu();
        Agregar = new javax.swing.JMenu();

        Comprar.setText("Comprar");
        Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Comprar);

        Rentar.setText("Para llevar");
        Rentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Rentar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu ArcadeDan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        saludo.setText("jLabel1");

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        cerrarS.setText("Cerrar Sesion");
        cerrarS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSMouseClicked(evt);
            }
        });

        eslogan.setText("jLabel1");

        jPanel1.setToolTipText("");

        VentaRentaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        VentaRentaPro.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(VentaRentaPro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        PersonasRenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(PersonasRenta);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Eliminar.setText("Eliminar");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Eliminar);

        Actualizar.setText("Actualizar");
        Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActualizarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Actualizar);

        Agregar.setText("Agregar");
        Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarMouseClicked(evt);
            }
        });
        jMenuBar1.add(Agregar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cerrarS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eslogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(saludo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saludo)
                        .addGap(11, 11, 11)
                        .addComponent(eslogan)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cerrarS)
                    .addComponent(salir)))
        );

        jPanel1.getAccessibleContext().setAccessibleName("Renta ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon obj = new ImageIcon(getClass().getResource("/ImagenesArcade/ventanas.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(icono);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Compra o Delivery de productos"));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Delivery de los clientes"));
        bienvenida();
        tablaRenta();
        tablaCompraVenta();
        if (l.getAdmin()) {
            jMenuBar1.setVisible(true);
            saludo.setText(saludo.getText() + " Admin");

        } else {
            jMenuBar1.setVisible(false);
        }
    }//GEN-LAST:event_formWindowActivated

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void cerrarSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSMouseClicked
        l.setVisible(true);
        l.setEncontro(false);
        this.dispose();
    }//GEN-LAST:event_cerrarSMouseClicked

    private void ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarActionPerformed
        Vender v = new Vender();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ComprarActionPerformed

    private void RentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentarActionPerformed
        rentaTeEsta();
        tablaRenta();
        tablaCompraVenta();
    }//GEN-LAST:event_RentarActionPerformed

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        Eliminar e = new Eliminar();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EliminarMouseClicked

    private void ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActualizarMouseClicked
     Actualizar a = new Actualizar();
     a.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_ActualizarMouseClicked

    private void AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMouseClicked
        Agregar agregar = new Agregar();
        agregar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AgregarMouseClicked

    public void rentaTeEsta() {
        try {
            String idVenta = "";
            String update = "";
            String cantidad = "";

            int filas = VentaRentaPro.getSelectedRow();
            if (filas >= 0) {
                idVenta = ((VentaRentaPro.getValueAt(filas, 0).toString()));
                cantidad = ((VentaRentaPro.getValueAt(filas, 3).toString()));

            }
            int cantidadF = Integer.parseInt(cantidad);
            cantidadF = cantidadF - 1;
            cantidad = String.valueOf(cantidadF);
            String insert = "";
            update = "UPDATE venta SET Cantidad = '" + cantidad + "' where venta.idVenta=" + idVenta + ";";
            insert = "INSERT INTO `renta` (`idRenta`, `Estado`, `FKventa`, `FKCliente`, `FKproducto`) VALUES (NULL, 'Renta', '" + idVenta + "', '" + l.getValorId() + "', '" + IdProducto() + "');";
            PreparedStatement pst = cn.prepareStatement(insert);
            PreparedStatement pst2 = cn.prepareStatement(update);

            pst.executeUpdate();
            pst2.executeUpdate();

        } catch (NumberFormatException | SQLException e) {
            System.out.println("Error en insertar " + e.getMessage());
        }

    }

    public void tablaRenta() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Usuario");
        modelo.addColumn("Estado");
        modelo.addColumn("Juego");

        PersonasRenta.setModel(modelo);
        String sql = "";
        sql = "select login.Nombre, login.Apellido, login.Usuario, productos.Nombre, Estado from renta inner join productos on idProducto=FKproducto inner join login on login.idLogin=renta.FKCliente inner join venta on venta.idVenta= FKventa and Estado='Renta';";
        String[] datos = new String[5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                modelo.addRow(datos);
            }
            PersonasRenta.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println("Error " + ex);
        }
    }

    public void tablaCompraVenta() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo producto");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Canitdad");
        modelo.addColumn("Precio");
        VentaRentaPro.setModel(modelo);
        String sql;
        sql = "select idVenta, productos.Nombre, DescripcionPro, cantidad, precio from venta inner join productos on FKProducto=idProducto order by idVenta;";
        String[] datos = new String[5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                modelo.addRow(datos);
            }
            VentaRentaPro.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println("Error " + ex);
        }
    }

    public void bienvenida() {
        saludo.setText("Bienvenido(a) " + l.getNombre());
        System.out.println("valor de encontro; " + l.getEncontro());
        System.out.println("valor de nombre; " + l.getNombre());
        eslogan.setText("Al arcadeDan donde Sacas a tu niño interior");
    }

    public String IdProducto() {
        String idProducto = "";
        try {
            String sql = "";

            String articulo = "";
            String idVenta = "";
            int filas = VentaRentaPro.getSelectedRow();
            if (filas >= 0) {
                idVenta = ((VentaRentaPro.getValueAt(filas, 0).toString()));
                articulo = ((VentaRentaPro.getValueAt(filas, 1).toString()));
            }
            System.out.println("valor de id Venta " + idVenta);
            System.out.println("valor de articulo: " + articulo);
            sql = "select idProducto from productos where productos.Nombre='" + articulo + "';";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if (rs.next()) {
                System.out.println("entro");
                idProducto = rs.getString(1);

                System.out.println("valor id Producto " + rs.getString(1));
            }
        } catch (Exception e) {
            System.out.println("Error en recibir idProducto: " + e.getMessage());
        }
        return idProducto;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arcade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arcade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arcade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arcade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arcade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Actualizar;
    private javax.swing.JMenu Agregar;
    private javax.swing.JMenuItem Comprar;
    private javax.swing.JMenu Eliminar;
    private javax.swing.JTable PersonasRenta;
    private javax.swing.JMenuItem Rentar;
    private javax.swing.JTable VentaRentaPro;
    private javax.swing.JButton cerrarS;
    private javax.swing.JLabel eslogan;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logo;
    private javax.swing.JButton salir;
    private javax.swing.JLabel saludo;
    // End of variables declaration//GEN-END:variables
Conexion cc = new Conexion();
    Connection cn = cc.conexion();
}
