/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arcade;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import prueba.Conexion;

/**
 *
 * @author DanKuzo
 */
public class Vender extends javax.swing.JFrame {

    Arcade arcade = new Arcade();
    Login l = new Login();

    /**
     * Creates new form Vender
     */
    public Vender() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        comprar = new javax.swing.JMenuItem();
        logo = new javax.swing.JLabel();
        Productos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VentaRentaPro = new javax.swing.JTable();
        saludo = new javax.swing.JLabel();
        eslogan = new javax.swing.JLabel();
        producto = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        pagarDirecto = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        regresar = new javax.swing.JButton();

        comprar.setText("Comprar");
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(comprar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compra ArcadeDan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        VentaRentaPro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        VentaRentaPro.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(VentaRentaPro);

        javax.swing.GroupLayout ProductosLayout = new javax.swing.GroupLayout(Productos);
        Productos.setLayout(ProductosLayout);
        ProductosLayout.setHorizontalGroup(
            ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        ProductosLayout.setVerticalGroup(
            ProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saludo.setText("jLabel1");

        eslogan.setText("jLabel1");

        producto.setText("Producto");

        precio.setText("Precio");

        total.setText("Total a pagar: ");

        pagarDirecto.setText("Pagar");
        pagarDirecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagarDirectoActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eslogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total)
                            .addComponent(pagarDirecto)
                            .addComponent(producto)
                            .addComponent(precio))
                        .addGap(0, 93, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(regresar)
                .addGap(19, 19, 19)
                .addComponent(salir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saludo)
                        .addGap(11, 11, 11)
                        .addComponent(eslogan)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(producto)
                        .addGap(27, 27, 27)
                        .addComponent(precio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salir)
                            .addComponent(regresar))
                        .addContainerGap())
                    .addComponent(pagarDirecto, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        Productos.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon obj = new ImageIcon(getClass().getResource("/ImagenesArcade/ventanas.png"));
        ImageIcon icono = new ImageIcon(obj.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(icono);
        pagarDirecto.setVisible(false);
        Productos.setBorder(javax.swing.BorderFactory.createTitledBorder("Escoja los productos"));
        tablaCompraVenta();
        bienvenida();
    }//GEN-LAST:event_formWindowActivated

    private void comprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprarActionPerformed
        mostrarInfo();
        pagarDirecto.setVisible(true);
    }//GEN-LAST:event_comprarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        arcade.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regresarActionPerformed

    private void pagarDirectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagarDirectoActionPerformed
        JOptionPane.showMessageDialog(null, "Gracias por su compra " + l.getNombre());
        pagoUnico();
        arcade.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pagarDirectoActionPerformed
    public void bienvenida() {
        saludo.setText("Hola de nuevo " + l.getNombre());
        System.out.println("valor de encontro; " + l.getEncontro());
        System.out.println("valor de nombre; " + l.getNombre());
        eslogan.setText("ArcadeDan donde Sacas a tu niño interior");
    }

    public void tablaCompraVenta() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo producto");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Canitdad");
        modelo.addColumn("Precio");
        VentaRentaPro.setModel(modelo);
        String sql;
        sql = "select idVenta, productos.Nombre, DescripcionPro, cantidad, precio from venta inner join productos on FKProducto=idProducto order by idVenta;";
        String[] datos = new String[5];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                System.out.println(datos[4]);
                modelo.addRow(datos);
            }
            VentaRentaPro.setModel(modelo);
        } catch (SQLException ex) {
            System.out.println("Error " + ex);
        }
    }

    public void mostrarInfo() {
        int filas = VentaRentaPro.getSelectedRow();
        if (filas >= 0) {
            producto.setText("Producto: " + (VentaRentaPro.getValueAt(filas, 1).toString()));
            precio.setText("Precio: $" + VentaRentaPro.getValueAt(filas, 4).toString() + " Pesos");
            total.setText("Total a pagar: $" + VentaRentaPro.getValueAt(filas, 4).toString() + " Pesos");
        } else {
            JOptionPane.showMessageDialog(null, "No hay filas seleccionadas");
        }

    }

    public void pagoUnico() {
        try {
            int filas = VentaRentaPro.getSelectedRow();
            String cantidad = "";
            String idVenta = "";
            if (filas >= 0) {
                idVenta = ((VentaRentaPro.getValueAt(filas, 0).toString()));
                cantidad = ((VentaRentaPro.getValueAt(filas, 3).toString()));

            }
            System.out.println("valor de cantidad antes de restar: " + cantidad);
            int cantidadF = Integer.parseInt(cantidad);
            cantidadF = cantidadF - 1;
            cantidad = String.valueOf(cantidadF);
            System.out.println("valor de cantidad: " + cantidad);
            String update = "UPDATE venta SET Cantidad = '" + cantidad + "' where venta.idVenta='"+idVenta+"'";
            PreparedStatement pst = cn.prepareStatement(update);
            pst.executeUpdate();
        } catch (Exception e) {
            System.out.println("Error al Actulizar la Cantidad " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Productos;
    private javax.swing.JTable VentaRentaPro;
    private javax.swing.JMenuItem comprar;
    private javax.swing.JLabel eslogan;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    private javax.swing.JButton pagarDirecto;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel producto;
    private javax.swing.JButton regresar;
    private javax.swing.JButton salir;
    private javax.swing.JLabel saludo;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
Conexion cc = new Conexion();
    Connection cn = cc.conexion();
}
